name: vote38
description: "A transparent, secure, and verifiable voting system using the Stellar blockchain."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: 5.0.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dice_bear: ^0.1.7
  file_picker: ^8.0.3
  firebase_auth: 5.1.0
  firebase_core: 3.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_mobx: ^2.2.1+1
  flutter_secure_storage: ^9.1.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: 13.2.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  measure_size: ^4.0.0
  minio:
    git:
      url: https://github.com/godilite/minio-dart.git
      ref: master
  mobx: ^2.3.3+2
  moon_design: ^0.59.0
  onboarding: ^4.0.2
  qr_flutter: ^4.1.0
  random_avatar: ^0.0.8
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  stellar_flutter_sdk: 1.8.0
  toastification: ^2.0.0
  tutorial_coach_mark: ^1.2.11
  url_launcher: ^6.3.0
  widgets_to_image: ^1.0.0
  
  

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  lint: 2.3.0
  mobx_codegen: ^2.6.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: RubikGlitchPop
      fonts:
        - asset: fonts/RubikGlitchPop-Regular.ttf
    - family: RedHatText
      fonts:
        - asset: fonts/RedHatText-Regular.ttf
        - asset: fonts/RedHatText-Bold.ttf
        - asset: fonts/RedHatText-Medium.ttf
        - asset: fonts/RedHatText-SemiBold.ttf
        - asset: fonts/RedHatText-Light.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Regular.ttf
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Medium.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
